// Bedenk zelf leesbare variabelen om volgende zin
// op het scherm te laten verschijnen:
// Goedemorgen mevr. Deleye, vandaag heeft u op de planning: vergadering met regionaal manager Sufyan Y.
// var ...
// var ...
// ...
// console.log(...);